song_table = {
     "Q1": {"filename": "/music/Billy Joel/Storm Front/02 We Didn't Start The Fire.wav", "artist": "Billy Joel", "song": "We didn't Start The Fire"},
     "K10": {"filename": "tone:10000", "artist": "Test Tone", "song": "10000"},
     "D10": {"filename": "radio:99.1", "artist": "Radio", "song": "99.1"},
     "E10": {"filename": "tone:63", "artist": "Test Tone", "song": "63"},
     "S1": {"filename": "/music/Cher/Believe/01 Believe.wav", "artist": "Cher", "song": "Believe"},
     "U1": {"filename": "/music/Cyndi Lauper/She's So Unusual/02 Girls Just Want To Have Fun.wav", "artist": "Cyndi Lauper", "song": "Girls Just Want To Have Fun"},
     "K2": {"filename": "/music/Duran Duran/Greatest/07 Hungry Like The Wolf.wav", "artist": "Duran Duran", "song": "Hungry Like the Wolf"},
     "K1": {"filename": "/music/Blondie/Rockbird/09 Beyond The Limit.wav", "artist": "Blondie", "song": "Beyond the Limit"},
     "M1": {"filename": "/music/Animotion/Obsession - The Best Of Animotion/04 I Engineer.wav", "artist": "Animotion", "song": "I Engineer"},
     "B10": {"filename": "radio:94.5", "artist": "Radio", "song": "94.5"},
     "M2": {"filename": "/music/Elton John/Greatest Hits 1976-1986/06 Don't Go Breaking My Heart.wav", "artist": "Elton John", "song": "Don't Go Breaking My Heart"},
     "U10": {"filename": "/music/Royalty Free/Kevin MacLeod/incompetech-AndroidSockHop.wav", "artist": "Kevin MacLeod", "song": "Android Sock Hop"},
     "C10": {"filename": "radio:96.1", "artist": "Radio", "song": "96.1"},
     "P10": {"filename": "/music/Royalty Free/Kevin MacLeod/incompetech-Metalmania.wav", "artist": "Kevin MacLeod", "song": "Metalmania"},
     "G2": {"filename": "/music/Dire Straits/Brothers In Arms/02 Money for Nothing.wav", "artist": "Dire Straits", "song": "Money For Nothing"},
     "G1": {"filename": "/music/Blondie/KooKoo/01 Jump Jump.wav", "artist": "Blondie", "song": "Jump Jump"},
     "S10": {"filename": "/music/Royalty Free/Kevin MacLeod/incompetech-Rocket.wav", "artist": "Kevin MacLeod", "song": "Rocket"},
     "A1": {"filename": "/music/Blondie/The Best Of Blondie/01 Heart Of Glass.wav", "artist": "Blondie", "song": "Heart Of Glass"},
     "V1": {"filename": "/music/Cyndi Lauper/She's So Unusual/06 All Through The Night.wav", "artist": "Cyndi Lauper", "song": "All Through The Night"},
     "A2": {"filename": "/music/David Bowie/Bowie_ The Singles 1969-1993 (Disc 1)/01 Space Oddity.wav", "artist": "David Bowie", "song": "Space Oddity"},
     "Q10": {"filename": "/music/Royalty Free/Kevin MacLeod/incompetech-Misuse.wav", "artist": "Kevin MacLeod", "song": "Misuse"},
     "C2": {"filename": "/music/David Bowie/Bowie_ The Singles 1969-1993 (Disc 1)/06 Starman.wav", "artist": "David Bowie", "song": "Starman"},
     "C1": {"filename": "/music/Blondie/The Best Of Blondie/05 Sunday Girl.wav", "artist": "Blondie", "song": "Sunday Girl"},
     "G10": {"filename": "tone:330", "artist": "Test Tone", "song": "330"},
     "E1": {"filename": "/music/Blondie/No Exit/01 Screaming Skin.wav", "artist": "Blondie", "song": "Screaming Skin"},
     "J10": {"filename": "tone:3300", "artist": "Test Tone", "song": "3300"},
     "E2": {"filename": "/music/David Bowie/Bowie_ The Singles 1969-1993 (Disc 2)/08 Under Pressure [with Queen].wav", "artist": "David Bowie", "song": "Under Pressure"},
     "P1": {"filename": "/music/Bangles/Greatest Hits/05 Walk Like An Egyptian.wav", "artist": "Bangles", "song": "Walk Like an Egyption"},
     "R1": {"filename": "/music/Billy Joel/Storm Front/04 I Go To Extremes.wav", "artist": "Billy Joel", "song": "I Go To Extrmes"},
     "H10": {"filename": "tone:1000", "artist": "Test Tone", "song": "1000"},
     "L10": {"filename": "tone:15000", "artist": "Test Tone", "song": "15000"},
     "N10": {"filename": "/music/Royalty Free/Kevin MacLeod/incompetech-ExitThePremises.wav", "artist": "Kevin MacLeod", "song": "Exit The Premesis"},
     "T1": {"filename": "/music/Cher/Believe/03 Runaway.wav", "artist": "Cher", "song": "Runaway"},
     "L2": {"filename": "/music/Elton John/Greatest Hits 1976-1986/01 I'm Still Standing.wav", "artist": "Elton John", "song": "I'm Still Standing"},
     "L1": {"filename": "/music/Animotion/Obsession - The Best Of Animotion/01 Obsession.wav", "artist": "Animotion", "song": "Obsession"},
     "N1": {"filename": "/music/Bangles/Greatest Hits/03 Manic Monday.wav", "artist": "Bangles", "song": "Manic Monday"},
     "F10": {"filename": "tone:150", "artist": "Test Tone", "song": "150"},
     "A10": {"filename": "radio:91.9", "artist": "Radio", "song": "91.9"},
     "F1": {"filename": "/music/Blondie/No Exit/02 Forgive And Forget.wav", "artist": "Blondie", "song": "Forgive and Forget"},
     "F2": {"filename": "/music/David Bowie/Bowie_ The Singles 1969-1993 (Disc 2)/15 Dancing in the Street [with Mick Jagger].wav", "artist": "David Bowie", "song": "Dancing in the Street"},
     "R10": {"filename": "/music/Royalty Free/Kevin MacLeod/incompetech-ReadyAimFire.wav", "artist": "Kevin MacLeod", "song": "Ready Aim Fire"},
     "H2": {"filename": "/music/Dire Straits/On Every Street/02 On Every Street.wav", "artist": "Dire Straits", "song": "On Every Street"},
     "V10": {"filename": "/music/Royalty Free/Kevin MacLeod/incompetech-GraveyardShift.wav", "artist": "Kevin MacLeod", "song": "Graveyard Shift"},
     "H1": {"filename": "/music/Blondie/KooKoo/06 Backfired.wav", "artist": "Blondie", "song": "Backfired"},
     "J1": {"filename": "/music/Blondie/Rockbird/07 Rockbird.wav", "artist": "Blondie", "song": "Rockbird"},
     "J2": {"filename": "/music/Duran Duran/Greatest/03 A View To A Kill.wav", "artist": "Duran Duran", "song": "A View To A Kill"},
     "M10": {"filename": "tone:33000", "artist": "Test Tone", "song": "33000"},
     "B1": {"filename": "/music/Blondie/The Best Of Blondie/03 The Tide Is High.wav", "artist": "Blondie", "song": "The Tide is High"},
     "B2": {"filename": "/music/David Bowie/Bowie_ The Singles 1969-1993 (Disc 1)/04 Life on Mars_.wav", "artist": "David Bowie", "song": "Life On Mars"},
     "T10": {"filename": "/music/Royalty Free/Kevin MacLeod/incompetech-SevereTireDamage.wav", "artist": "Kevin MacLeod", "song": "Severe Tire Damage"},
     "D2": {"filename": "/music/David Bowie/Bowie_ The Singles 1969-1993 (Disc 1)/15 Fame.wav", "artist": "David Bowie", "song": "Fame"},
     "D1": {"filename": "/music/Blondie/The Best Of Blondie/08 One Way Or Another.wav", "artist": "Blondie", "song": "One Way Or Another"},
}
