song_table = {
     "G7": {"filename": "/music/The B-52's/the B-52's/04 Rock Lobster.wav", "artist": "The B-52's", "song": "Rock Lobster"},
     "G6": {"filename": "tone:330", "artist": "Test Tone", "song": "330"},
     "G5": {"filename": "/music/Richard Marx/Paid Vacation/03 Silent Scream.wav", "artist": "Richard Marx", "song": "Silent Scream"},
     "G4": {"filename": "/music/Meat Loaf/Bat Out Of Hell II - Back Into Hell/01 I'd Do Anything For Love (But I Won't Do That).wav", "artist": "Meat Loaf", "song": "I'd do Anything for Love"},
     "G3": {"filename": "/music/Inxs/Live Baby Live/01 New Sensation.wav", "artist": "Inxs", "song": "New Sensation"},
     "G2": {"filename": "/music/Dire Straits/Brothers In Arms/02 Money for Nothing.wav", "artist": "Dire Straits", "song": "Money For Nothing"},
     "G1": {"filename": "/music/Blondie/KooKoo/01 Jump Jump.wav", "artist": "Blondie", "song": "Jump Jump"},
     "V2": {"filename": "/music/Genesis/Live-The Way We Walk/05 I Can't Dance.wav", "artist": "Genesis", "song": "I Can't Dance"},
     "V3": {"filename": "/music/Madonna/The Immaculate Collection/13 EXPRESS YOURSELF.wav", "artist": "Madonna", "song": "Express Yourself"},
     "V4": {"filename": "/music/Pat Benatar/Crimes of Passion/09 Prisoner Of Love.wav", "artist": "Pat Benatar", "song": "Prisoner Of Love"},
     "V5": {"filename": "/music/Styx/Greatest Hits/16 Don't Let it End.wav", "artist": "Styx", "song": "Don't Let it End"},
     "R4": {"filename": "/music/Nena/99 Luftballons/04 Just A Dream.wav", "artist": "Nena", "song": "Just A Dream"},
     "R5": {"filename": "/music/Sting/Every Breath You Take - The Singles/11 King of Pain.wav", "artist": "Sting", "song": "King of Pain"},
     "R6": {"filename": "/music/Royalty Free/Kevin MacLeod/incompetech-ReadyAimFire.wav", "artist": "Kevin MacLeod", "song": "Ready Aim Fire"},
     "R7": {"filename": "/music/UB40/Promises And Lies/08 Now And Then.wav", "artist": "UB40", "song": "Now And Then"},
     "R1": {"filename": "/music/Billy Joel/Storm Front/04 I Go To Extremes.wav", "artist": "Billy Joel", "song": "I Go To Extrmes"},
     "R2": {"filename": "/music/Eurythmics/Greatest Hits/08 Missionary Man.wav", "artist": "Eurythmics", "song": "Missionary Man"},
     "R3": {"filename": "/music/Laura Branigan/The Best Of Branigan/07 Dim All The Lights.wav", "artist": "Laura Branigan", "song": "Dim All The Lights"},
     "V7": {"filename": "/music/Various Artists/The 80's Hot Dance Trax/09 The Loco-Motion - Kylie Minogue.wav", "artist": "Various Artists", "song": "The Loco-Motion"},
     "J4": {"filename": "/music/Melissa Etheridge/YES I AM/01 Im The Only One.wav", "artist": "Melissa Etheridge", "song": "I'm The Only One"},
     "J5": {"filename": "/music/Sheryl Crow/Tuesday Night Music Club/02 Leaving Las Vegas.wav", "artist": "Sheryl Crow", "song": "Leaving Las Vegas"},
     "J6": {"filename": "tone:3300", "artist": "Test Tone", "song": "3300"},
     "J7": {"filename": "/music/Tina Turner/Simply The Best/11 We Don't Need Another Hero.wav", "artist": "Tina Turner", "song": "We Don't Need Another Hero"},
     "J1": {"filename": "/music/Blondie/Rockbird/07 Rockbird.wav", "artist": "Blondie", "song": "Rockbird"},
     "J2": {"filename": "/music/Duran Duran/Greatest/03 A View To A Kill.wav", "artist": "Duran Duran", "song": "A View To A Kill"},
     "J3": {"filename": "/music/Joni Mitchell/Turbulent Indigo/01 Sunny Sunday.wav", "artist": "Joni Mitchell", "song": "Sunday Sunday"},
     "B4": {"filename": "/music/Madonna/Erotica/10 Rain.wav", "artist": "Madonna", "song": "Rain"},
     "B5": {"filename": "/music/Paul Simon/Graceland/05 Diamonds On The Soles Of Her Shoes.wav", "artist": "Paul Simon", "song": "Diamonds On The Soles Of Her Shoes"},
     "B6": {"filename": "radio:94.5", "artist": "Radio", "song": "94.5"},
     "B7": {"filename": "/music/Suzanne Vega/999F/02 Blood Makes Noise.wav", "artist": "Suzanne Vega", "song": "Blood Makes Noise"},
     "B1": {"filename": "/music/Blondie/The Best Of Blondie/03 The Tide Is High.wav", "artist": "Blondie", "song": "The Tide is High"},
     "B2": {"filename": "/music/David Bowie/Bowie_ The Singles 1969-1993 (Disc 1)/04 Life on Mars_.wav", "artist": "David Bowie", "song": "Life On Mars"},
     "B3": {"filename": "/music/Go Go's/Greatest/06 Vacation.wav", "artist": "Go Go's", "song": "Vacation"},
     "U5": {"filename": "/music/Styx/Greatest Hits/06 Fooling Yourself (The Angry Young Man).wav", "artist": "Styx", "song": "Fooling Yourself"},
     "U4": {"filename": "/music/Pat Benatar/Crimes of Passion/05 Hell Is For Children.wav", "artist": "Pat Benatar", "song": "Hell Is For Children"},
     "U7": {"filename": "/music/Various Artists/The 80's Hot Dance Trax/06 You Keep Me Hangin' On - Kim Wilde.wav", "artist": "Various Artists", "song": "You Keep Me Hangin' On"},
     "U6": {"filename": "/music/Royalty Free/Kevin MacLeod/incompetech-AndroidSockHop.wav", "artist": "Kevin MacLeod", "song": "Android Sock Hop"},
     "U1": {"filename": "/music/Cyndi Lauper/She's So Unusual/02 Girls Just Want To Have Fun.wav", "artist": "Cyndi Lauper", "song": "Girls Just Want To Have Fun"},
     "U3": {"filename": "/music/Madonna/The Immaculate Collection/05 MATERIAL GIRL.wav", "artist": "Madonna", "song": "Material Girl"},
     "U2": {"filename": "/music/Genesis/Live-The Way We Walk/01 Land Of Confusion.wav", "artist": "Genesis", "song": "Land of Confusion"},
     "M5": {"filename": "/music/Siouxsie And The Banshees/Twice Upon A Time The Singles/18 Face To Face.wav", "artist": "Siouxsie And The Banshees", "song": "Face To Face"},
     "M4": {"filename": "/music/Missing Persons/The Best Of Missing Persons/02 Destination Unknown.wav", "artist": "Missing Persons", "song": "Destination Unkown"},
     "M7": {"filename": "/music/Tom Petty/Greatest Hits/11 Don't Come Around Here No More.wav", "artist": "Tom Petty", "song": "Don't Come Around Here No More"},
     "M6": {"filename": "tone:33000", "artist": "Test Tone", "song": "33000"},
     "M1": {"filename": "/music/Animotion/Obsession - The Best Of Animotion/04 I Engineer.wav", "artist": "Animotion", "song": "I Engineer"},
     "M3": {"filename": "/music/Kd lang/Ingenue/10 Constant Craving.wav", "artist": "KD Lang", "song": "Constant Craving"},
     "M2": {"filename": "/music/Elton John/Greatest Hits 1976-1986/06 Don't Go Breaking My Heart.wav", "artist": "Elton John", "song": "Don't Go Breaking My Heart"},
     "A7": {"filename": "/music/Suzanne Vega/999F/04 999F.wav", "artist": "Suzanne Vega", "song": "99.9F"},
     "E5": {"filename": "/music/Peter Gabriel/Shaking The Tree/12 Shock The Monkey.wav", "artist": "Peter Gabriel", "song": "Shock The Monkey"},
     "E4": {"filename": "/music/Madonna/Ray of Light/03 Ray Of Light.wav", "artist": "Madonna", "song": "Ray Of Light"},
     "E7": {"filename": "/music/Suzanne Vega/Solitude Standing/07 Calypso.wav", "artist": "Suzanne Vega", "song": "Calypso"},
     "E6": {"filename": "tone:63", "artist": "Test Tone", "song": "63"},
     "E1": {"filename": "/music/Blondie/No Exit/01 Screaming Skin.wav", "artist": "Blondie", "song": "Screaming Skin"},
     "E3": {"filename": "/music/Grace Jones/Island Life/03 Do or die.wav", "artist": "Grace Jones", "song": "Do or Die"},
     "E2": {"filename": "/music/David Bowie/Bowie_ The Singles 1969-1993 (Disc 2)/08 Under Pressure [with Queen].wav", "artist": "David Bowie", "song": "Under Pressure"},
     "P2": {"filename": "/music/Enya/A Day Without Rain/Lazy Days.wav", "artist": "Enya", "song": "Lazy Days"},
     "P3": {"filename": "/music/Laura Branigan/The Best Of Branigan/13 Gloria.wav", "artist": "Laura Branigan", "song": "Gloria"},
     "P1": {"filename": "/music/Bangles/Greatest Hits/05 Walk Like An Egyptian.wav", "artist": "Bangles", "song": "Walk Like an Egyption"},
     "P6": {"filename": "/music/Royalty Free/Kevin MacLeod/incompetech-Metalmania.wav", "artist": "Kevin MacLeod", "song": "Metalmania"},
     "P7": {"filename": "/music/Tom Petty/Greatest Hits/15 Learning To Fly.wav", "artist": "Tom Petty", "song": "Learning To Fly"},
     "P4": {"filename": "/music/Missing Persons/The Best Of Missing Persons/14 I Can't Think About Dancin'.wav", "artist": "Missing Persons", "song": "I Can't Think About Dancin'"},
     "P5": {"filename": "/music/Sting/Every Breath You Take - The Singles/05 Don't Stand So Close to Me '86.wav", "artist": "Sting", "song": "Don't Stand So Close To Me"},
     "H2": {"filename": "/music/Dire Straits/On Every Street/02 On Every Street.wav", "artist": "Dire Straits", "song": "On Every Street"},
     "H3": {"filename": "/music/Inxs/Live Baby Live/01 New Sensation.wav", "artist": "Inxs", "song": "Guns in the Sky"},
     "H1": {"filename": "/music/Blondie/KooKoo/06 Backfired.wav", "artist": "Blondie", "song": "Backfired"},
     "H6": {"filename": "tone:1000", "artist": "Test Tone", "song": "1000"},
     "H7": {"filename": "/music/The B-52's/the B-52's/05 Lava.wav", "artist": "The B-52's", "song": "Lava"},
     "H4": {"filename": "/music/Meat Loaf/Bat Out Of Hell II - Back Into Hell/10 Back Into Hell.wav", "artist": "Meat Loaf", "song": "Back Into Hell"},
     "H5": {"filename": "/music/Richard Marx/Paid Vacation/04 Nothing to Hide.wav", "artist": "Richard Marx", "song": "Nothing To Hide"},
     "S3": {"filename": "/music/Madonna/The Immaculate Collection/01 HOLIDAY.wav", "artist": "Madonna", "song": "Holiday"},
     "S2": {"filename": "/music/Eurythmics/Diva/02 Walking On Broken Glass.wav", "artist": "Eurythmics", "song": "Walking on Broken Glass"},
     "S1": {"filename": "/music/Cher/Believe/01 Believe.wav", "artist": "Cher", "song": "Believe"},
     "S7": {"filename": "/music/Various Artists/The 80's Hot Dance Trax/01 Venus - Bananarama.wav", "artist": "Various Artists", "song": "Venus"},
     "S6": {"filename": "/music/Royalty Free/Kevin MacLeod/incompetech-Rocket.wav", "artist": "Kevin MacLeod", "song": "Rocket"},
     "S5": {"filename": "/music/Styx/Greatest Hits/04 Too Much Time on my Hands.wav", "artist": "Styx", "song": "Too Much Time on my Hands"},
     "S4": {"filename": "/music/Pat Benatar/Crimes of Passion/01 Treat Me Right.wav", "artist": "Pat Benatar", "song": "Treat Me Right"},
     "K3": {"filename": "/music/Joni Mitchell/Turbulent Indigo/08 Borderline.wav", "artist": "Joni Mitchell", "song": "Borderline"},
     "K2": {"filename": "/music/Duran Duran/Greatest/07 Hungry Like The Wolf.wav", "artist": "Duran Duran", "song": "Hungry Like the Wolf"},
     "K1": {"filename": "/music/Blondie/Rockbird/09 Beyond The Limit.wav", "artist": "Blondie", "song": "Beyond the Limit"},
     "K7": {"filename": "/music/Tina Turner/Simply The Best/06 Nutbush City Limits.wav", "artist": "Tina Turner", "song": "Nutbush City Limits"},
     "K6": {"filename": "tone:10000", "artist": "Test Tone", "song": "10000"},
     "K5": {"filename": "/music/Sheryl Crow/Tuesday Night Music Club/09 All I Wanna Do.wav", "artist": "Sheryl Crow", "song": "All I Wanna Do"},
     "K4": {"filename": "/music/Melissa Etheridge/YES I AM/07 Yes I Am.wav", "artist": "Melissa Etheridge", "song": "Yes I Am"},
     "C3": {"filename": "/music/Go Go's/Greatest/01 Our Lips Are Sealed.wav", "artist": "Go Go's", "song": "Our Lips Are Sealed"},
     "C2": {"filename": "/music/David Bowie/Bowie_ The Singles 1969-1993 (Disc 1)/06 Starman.wav", "artist": "David Bowie", "song": "Starman"},
     "C1": {"filename": "/music/Blondie/The Best Of Blondie/05 Sunday Girl.wav", "artist": "Blondie", "song": "Sunday Girl"},
     "C7": {"filename": "/music/Suzanne Vega/Solitude Standing/01 Tom's Diner.wav", "artist": "Suzanne Vega", "song": "Tom's Diner"},
     "C6": {"filename": "radio:96.1", "artist": "Radio", "song": "96.1"},
     "C5": {"filename": "/music/Peter Gabriel/Shaking The Tree/03 Sledgehammer.wav", "artist": "Peter Gabriel", "song": "Sledgehammer"},
     "C4": {"filename": "/music/Madonna/Music/01 Music.wav", "artist": "Madonna", "song": "Music"},
     "N1": {"filename": "/music/Bangles/Greatest Hits/03 Manic Monday.wav", "artist": "Bangles", "song": "Manic Monday"},
     "N2": {"filename": "/music/Enya/A Day Without Rain/A Day Without Rain.wav", "artist": "Enya", "song": "A Day Without Rain"},
     "N3": {"filename": "/music/Laura Branigan/The Best Of Branigan/12 Self Control.wav", "artist": "Laura Branigan", "song": "Self Control"},
     "N4": {"filename": "/music/Missing Persons/The Best Of Missing Persons/08 Walking In LA.wav", "artist": "Missing Persons", "song": "Walking in LA"},
     "N5": {"filename": "/music/Sting/Every Breath You Take - The Singles/01 Roxanne.wav", "artist": "Sting", "song": "Roxanne"},
     "N6": {"filename": "/music/Royalty Free/Kevin MacLeod/incompetech-ExitThePremises.wav", "artist": "Kevin MacLeod", "song": "Exit The Premesis"},
     "N7": {"filename": "/music/Tom Petty/Greatest Hits/12 I Won't Back Down.wav", "artist": "Tom Petty", "song": "I Won't Back Down"},
     "F1": {"filename": "/music/Blondie/No Exit/02 Forgive And Forget.wav", "artist": "Blondie", "song": "Forgive and Forget"},
     "F2": {"filename": "/music/David Bowie/Bowie_ The Singles 1969-1993 (Disc 2)/15 Dancing in the Street [with Mick Jagger].wav", "artist": "David Bowie", "song": "Dancing in the Street"},
     "F3": {"filename": "/music/Grace Jones/Island Life/10 Slave to the rhythm.wav", "artist": "Grace Jones", "song": "Slave to the rhythm"},
     "F4": {"filename": "/music/Madonna/Ray of Light/09 Frozen.wav", "artist": "Madonna", "song": "Frozen"},
     "F5": {"filename": "/music/Peter Gabriel/Shaking The Tree/14 Big Time.wav", "artist": "Peter Gabriel", "song": "Big Time"},
     "F6": {"filename": "tone:150", "artist": "Test Tone", "song": "150"},
     "F7": {"filename": "/music/Suzanne Vega/Solitude Standing/05 Night Vision.wav", "artist": "Suzanne Vega", "song": "Night Vision"},
     "Q1": {"filename": "/music/Billy Joel/Storm Front/02 We Didn't Start The Fire.wav", "artist": "Billy Joel", "song": "We didn't Start The Fire"},
     "Q3": {"filename": "/music/Laura Branigan/The Best Of Branigan/05 The Power Of Love.wav", "artist": "Laura Branigan", "song": "The Power Of Love"},
     "Q2": {"filename": "/music/Eurythmics/Greatest Hits/01 Sweet Dreams  are made of this.wav", "artist": "Eurythmics", "song": "Sweet Dreams"},
     "Q5": {"filename": "/music/Sting/Every Breath You Take - The Singles/10 Every Breath You Take.wav", "artist": "Sting", "song": "Every Breath You Take"},
     "Q4": {"filename": "/music/Nena/99 Luftballons/01 99 Red Balloons.wav", "artist": "Nena", "song": "99 Red Balloons"},
     "Q7": {"filename": "/music/UB40/Promises And Lies/07 Can't Help Falling In Love.wav", "artist": "UB40", "song": "Can't Help Falling In Love"},
     "Q6": {"filename": "/music/Royalty Free/Kevin MacLeod/incompetech-Misuse.wav", "artist": "Kevin MacLeod", "song": "Misuse"},
     "A1": {"filename": "/music/Blondie/The Best Of Blondie/01 Heart Of Glass.wav", "artist": "Blondie", "song": "Heart Of Glass"},
     "V1": {"filename": "/music/Cyndi Lauper/She's So Unusual/06 All Through The Night.wav", "artist": "Cyndi Lauper", "song": "All Through The Night"},
     "A3": {"filename": "/music/Go Go's/Greatest/03 We Got The Beat.wav", "artist": "Go Go's", "song": "We Got The Beat"},
     "A2": {"filename": "/music/David Bowie/Bowie_ The Singles 1969-1993 (Disc 1)/01 Space Oddity.wav", "artist": "David Bowie", "song": "Space Oddity"},
     "A5": {"filename": "/music/Paul Simon/Graceland/06 You Can Call Me Al.wav", "artist": "Paul Simon", "song": "You Can Call Me Al"},
     "A4": {"filename": "/music/Madonna/Erotica/01 Erotica.wav", "artist": "Madonna", "song": "Words"},
     "V6": {"filename": "/music/Royalty Free/Kevin MacLeod/incompetech-GraveyardShift.wav", "artist": "Kevin MacLeod", "song": "Graveyard Shift"},
     "A6": {"filename": "radio:91.9", "artist": "Radio", "song": "91.9"},
     "T6": {"filename": "/music/Royalty Free/Kevin MacLeod/incompetech-SevereTireDamage.wav", "artist": "Kevin MacLeod", "song": "Severe Tire Damage"},
     "T7": {"filename": "/music/Various Artists/The 80's Hot Dance Trax/02 Two Of Hearts - Stacey Q.wav", "artist": "Various Artists", "song": "Two Of Hearts"},
     "T4": {"filename": "/music/Pat Benatar/Crimes of Passion/04 Hit Me With Your Best Shot.wav", "artist": "Pat Benatar", "song": "Hit Me With Your Best Shot"},
     "T5": {"filename": "/music/Styx/Greatest Hits/15 Mr Roboto.wav", "artist": "Styx", "song": "Mr Roboto"},
     "T2": {"filename": "/music/Eurythmics/Diva/04 Legend In My Living Room.wav", "artist": "Eurythmics", "song": "Legend in my Living Room"},
     "T3": {"filename": "/music/Madonna/The Immaculate Collection/04 LIKE A VIRGIN.wav", "artist": "Madonna", "song": "Like a Virgin"},
     "T1": {"filename": "/music/Cher/Believe/03 Runaway.wav", "artist": "Cher", "song": "Runaway"},
     "L6": {"filename": "tone:15000", "artist": "Test Tone", "song": "15000"},
     "L7": {"filename": "/music/Tom Petty/Greatest Hits/02 Breakdown.wav", "artist": "Tom Petty", "song": "Breakdown"},
     "L4": {"filename": "/music/Missing Persons/The Best Of Missing Persons/01 Words.wav", "artist": "Missing Persons", "song": "Words"},
     "L5": {"filename": "/music/Siouxsie And The Banshees/Twice Upon A Time The Singles/01 Fireworks.wav", "artist": "Siouxsie And The Banshees", "song": "Fireworks"},
     "L2": {"filename": "/music/Elton John/Greatest Hits 1976-1986/01 I'm Still Standing.wav", "artist": "Elton John", "song": "I'm Still Standing"},
     "L3": {"filename": "/music/Kd lang/Ingenue/01 Save Me.wav", "artist": "KD Lang", "song": "Save Me"},
     "L1": {"filename": "/music/Animotion/Obsession - The Best Of Animotion/01 Obsession.wav", "artist": "Animotion", "song": "Obsession"},
     "D6": {"filename": "radio:99.1", "artist": "Radio", "song": "99.1"},
     "D7": {"filename": "/music/Suzanne Vega/Solitude Standing/02 Luka.wav", "artist": "Suzanne Vega", "song": "Luka"},
     "D4": {"filename": "/music/Madonna/Music/02 Impressive Instant.wav", "artist": "Madonna", "song": "Impressive Instance"},
     "D5": {"filename": "/music/Peter Gabriel/Shaking The Tree/Games Without Frontiers.wav", "artist": "Peter Gabriel", "song": "Games Without Frontiers"},
     "D2": {"filename": "/music/David Bowie/Bowie_ The Singles 1969-1993 (Disc 1)/15 Fame.wav", "artist": "David Bowie", "song": "Fame"},
     "D3": {"filename": "/music/Go Go's/Greatest/12 Mercenary.wav", "artist": "Go Go's", "song": "Mercenary"},
     "D1": {"filename": "/music/Blondie/The Best Of Blondie/08 One Way Or Another.wav", "artist": "Blondie", "song": "One Way Or Another"},
}
